App\Entity\User:
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 15
        email:
            - NotBlank: ~
            - Email: ~
            - Length:
                max: 180
        password:
            - NotBlank: ~
            - Length:
                min: 6
        role:
            - NotBlank: ~
            - Choice:
                choices: ['ROLE_USER', 'ROLE_ADMIN'] # Adjust roles as necessary
