# config/packages/validator.yaml

framework:
    validation:
        # Enables validator auto-mapping support.
        auto_mapping:
            App\Entity\:
                - App\Validator\YourCustomValidator # Si tienes validadores personalizados
        mapping:
            paths:
                - '%kernel.project_dir%/config/packages/validator'



when@test:
    framework:
        validation:
            not_compromised_password: false
